apiVersion: v1
kind: Service
metadata:
  name: {{ .ServiceName }}
  labels:
    app: {{ .ServiceName }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .ServicePort }}
      targetPort: {{ .ContainerPort }}
  selector:
    app: {{ .ServiceName }}
